### PR TITLE
Upon reading the code in the nif file and the descriptions this would…

### PR DESCRIPTION
**Pull request by Jokezor**
… handle the country code

### CODE REVIEW

**Comment by Jokezor** [comment]
```
"""NIF (Número de Identificación Fiscal, Spanish VAT number).

The Spanish VAT number is a 9-digit number where either the first, last
digits or both can be letters.

The number is either a DNI (Documento Nacional de Identidad, for
Spaniards), a NIE (Número de Identificación de Extranjero, for
foreigners) or a CIF (Código de Identificación Fiscal, for legal
entities and others).

>>> compact('ES B-58378431')
'B58378431'
>>> validate('B64717838')
'B64717838'
>>> validate('B64717839')  # invalid check digit
Traceback (most recent call last):
    ...
InvalidChecksum: ...
>>> validate('54362315K')  # resident
'54362315K'
>>> validate('X-5253868-R')  # foreign person
'X5253868R'
>>> validate('M-1234567-L')  # foreign person without NIE
'M1234567L'
"""
```

```
def compact(number):
    """Convert the number to the minimal representation. This strips the
    number of any valid separators and removes surrounding whitespace."""
    number = clean(number, ' -').upper().strip()
    if number.startswith('ES'):
        number = number[2:]
    return number


def validate(number):
    """Check if the number provided is a valid VAT number. This checks the
    length, formatting and check digit."""
    number = compact(number)
    if not isdigits(number[1:-1]):
        raise InvalidFormat()
    if len(number) != 9:
        raise InvalidLength()
    if number[0] in 'KLM':
        # K: Spanish younger than 14 year old
        # L: Spanish living outside Spain without DNI
        # M: granted the tax to foreigners who have no NIE
        # these use the old checkdigit algorithm (the DNI one)
        if number[-1] != dni.calc_check_digit(number[1:-1]):
            raise InvalidChecksum()
    elif isdigits(number[0]):
        # natural resident
        dni.validate(number)
    elif number[0] in 'XYZ':
        # foreign natural person
        nie.validate(number)
    else:
        # otherwise it has to be a valid CIF
        cif.validate(number)
    return number
```

**Review by EmberCraze — COMMENTED** [review]
LGTM

**Comment by EmberCraze** [comment]
But isnt the problem with nif that it might validate other numbers that are not cif? I could be wrong here

**Comment by Jokezor** [comment]
> But isnt the problem with nif that it might validate other numbers that are not cif? I could be wrong here

Yes, that is also true :P

I could either add the compact into CIF or keep this.
But this felt general and at least makes the validation pass :shrug:

**Comment by EmberCraze** [comment]
I am thinking that this also affects all normal users in the system ie recipient companies. I think it would be find to just check if the country code is added in the beginning of the number and just remove it in the compact method. This is what other VAT methods are doing

**Comment by EmberCraze** [comment]
This would suffice
```python
if number.startswith('ES'):
        number = number[2:]
```

**Review by EmberCraze — APPROVED** [review]

**Comment by EmberCraze** [comment]
Looks good!

**Pull request merged**
