### PR TITLE
feat: add support for singapore

### PR DESCRIPTION
**Pull request by EmberCraze**
Adds nric/fin number validation for singapore

### CODE REVIEW

**Comment by JoaBon** [comment]
What is the source for the calculation?

**Comment by EmberCraze** [comment]
> What is the source for the calculation?

https://github.com/samliew/singapore-nric

**Comment by JoaBon** [comment]
> > What is the source for the calculation?
> 
> https://github.com/samliew/singapore-nric

I think the source should be added to the `nric` file since it's not from stdnum.

**Comment by EmberCraze** [comment]
> > > What is the source for the calculation?
> > 
> > 
> > https://github.com/samliew/singapore-nric
> 
> I think the source should be added to the `nric` file since it's not from stdnum.

Done :P

**Review by JoaBon — APPROVED** [review]
LGTM

**Pull request merged**
